### ISSUE TITLE
[QUESTION] Using the sensor at lower duty cycles

### ISSUE THREAD

**Issue by oscgonfer** [Sensirion/arduino-gas-index-algorithm#2]
Hi!

Thanks for the library for this SPG40 Sensor.
We would like to ask about the low power modes and the limitations about the Gas Index Algorithm.

In particular, in the datasheet, it's specified that the `SRAW_VOC` measurements need to be fed into the Gas Index Algorithm every second. However, the low power table in your README indicates 10s.

Questions are:

. Is it possible to set an arbitrary interval for this data? In other words, can the Gas Index Algorithm be fed with data every 60s, or more?
. If a hard reset happens on the MCU performing this algorithm, the current values are lost. How is this handled? In our [particular application](https://github.com/fablabbcn/smartcitizen-kit-21), a hard reset takes place ever 24h on the main MCU. Does it makes sense to use the sensor in this type of application (low cost sensor device for AQ monitoring).

Thank you in advance

**Comment by psachs** [comment]
Hi,

It is possible to adjust the sampling interval to 10s and run it in low power mode. This is not documented in the Datasheet but in a specific application note.
We only tested the Algorithm for 1s and 10s. You are free to set any arbitrary sampling interval but we do not have any data on the performance of the algorithm in this case. E.g. if you feed the algorithm every 60s as you suggested the performance will suffer for sure and you will most certainly miss short term VOC events.

If you have a hard reset every 24h you have to make sure to save and restore the state in between to ensure the algorithm keeps it's history.
Please note that for the first 60s after restart the algorithm will always output 0 even if you restore the state to ensure a stable start.

Best regards,
Pascal

**Comment by oscgonfer** [comment]
Hi @psachs, sorry for not replying to this sooner. Thank you very much for the response. We are going to test this internally and maybe write back in here.
