### ISSUE TITLE
[Q] Low Power example doesn't allow setting NOx sample interval

### ISSUE THREAD

**Issue by tonhuisman** [Sensirion/arduino-gas-index-algorithm#3]
When extending the Low Power example to use the SGP41 sensor, for `NOxGasIndexAlgorithm` there is no constructor available to set the sample interval. Shouldn't that constructor be added in the header file? (I've added in my local copy, just to have it consistent with the `VOCGasIndexAlgorithm`).
Or are there reasons that no interval, other than the default, should be used?

**Comment by sdmueller** [comment]
Hi @tonhuisman 

Unfortunately, the `NOxGasIndexAlgorithm` does not support different sample intervals unlike the `VOCGasIndexAlgorithm`.
Thats why the constructor for the `NOxGasIndexAlgorithm` does not have the option to set it.

I am closing the issue but feel free to reopen if you have any further questions.
